apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-object-store-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: ceph-object-store
  objectStoreNamespace: rook-ceph
  region: us-west-1
